/**
 * Agent-to-Agent chat server.
 *
 * Zero dependencies: node:net + newline-delimited JSON.
 * Run manually:  node server.mjs
 * Or let the pi extension (agent-chat.ts) spawn it detached on first use.
 * Single instance per machine: a second server exits on EADDRINUSE.
 *
 * Send flow: onSend assigns a mid, forwards {type:"message",mid} to the
 * targets and holds the sender's rid. Receivers ack per mid ("buffered" /
 * "delivered" / "failed"); the reply goes out when every target reached a
 * terminal state or after 5s, whichever first. The mid mapping is dropped
 * on reply, so late acks are ignored. Target stages only move up the rank
 * pending < buffered < delivered < failed (a "delivered" ack may race
 * ahead of "buffered"; "failed" is sticky).
 *
 * When stdout is a TTY (started by a user in a terminal), each send renders
 * a live status frame that is redrawn in place on every ack.
 */
import net from "node:net";

const HOST = "127.0.0.1";
const PORT = Number(process.env.AGENT_CHAT_PORT ?? 41729);
const ACK_WINDOW_MS = 5000;

/** sock -> { sock, name, pid, cwd, task } */
const users = new Map();

/** mid -> { sock, rid, from, text, status: Map<target, stage>, drawn } */
const pendingSends = new Map();
let midCounter = 0;
const RANK = { pending: 0, buffered: 1, delivered: 2, failed: 3 };
const isSettled = (p) => [...p.status.values()].every((v) => v === "delivered" || v === "failed");

const now = () => new Date().toISOString().replace("T", " ").slice(0, 19);
const all = () => [...users.values()];
const find = (name) => all().find((u) => u.name === name);

const isTTY = !!process.stdout.isTTY || !!process.env.AGENT_CHAT_FORCE_TTY;
const paint = (code, s) => (isTTY && !process.env.NO_COLOR ? `\x1b[${code}m${s}\x1b[0m` : s);

/** Live send status frame, redrawn in place on every ack. Single write per redraw. */
function drawFrame(p) {
	if (!isTTY) return;
	const sep = "--------------------------";
	const grp = (stage) => [...p.status].filter(([, v]) => v === stage).map(([k]) => k).join(", ");
	const lines = [
		paint(90, sep),
		`${paint(90, now().slice(11))} ${paint(36, p.from)}${paint(33, ` -> ${[...p.status.keys()].join(", ") || "(none)"}`)}`,
		p.text,
		paint(90, "---"),
		...(p.status.size === 0
			? [paint(32, "Success, but there are no other agents on the server.")]
			: [
					paint(32, `Received and already read: ${grp("delivered")}`),
					paint(33, `Received, agent busy and temporarily unread in 5s: ${grp("buffered")}`),
					paint(31, `Failed to receive: ${grp("failed")}`),
				]),
		paint(90, sep),
		paint(90, sep),
	];
	const body = lines.map((l) => `\x1b[2K${l}`).join("\n") + "\n";
	process.stdout.write(p.drawn ? `\x1b[${p.drawn}A${body}` : body);
	p.drawn = lines.length;
}

function send(sock, obj) {
	if (!sock || sock.destroyed) return false;
	try {
		sock.write(JSON.stringify(obj) + "\n");
		return true;
	} catch {
		return false;
	}
}

function broadcast(obj, except) {
	for (const sock of users.keys()) {
		if (sock !== except) send(sock, obj);
	}
}

function handle(sock, line) {
	let m;
	try {
		m = JSON.parse(line);
	} catch {
		return send(sock, { type: "error", message: "Bad JSON." });
	}
	// Replies echo the request's rid so the client can match them.
	const rid = m.rid;
	if (m.type === "register") return onRegister(sock, m, rid);
	if (m.type === "list") return onList(sock, rid);
	if (m.type === "send") return onSend(sock, m, rid);
	if (m.type === "ack") return onAck(sock, m); // receiver push, no rid
	send(sock, { type: "error", message: `Unknown request type: ${m.type}`, rid });
}

function onRegister(sock, m, rid) {
	const pid = Number(m.pid);
	if (!Number.isInteger(pid) || pid <= 0) {
		return send(sock, { type: "error", message: "Invalid pid.", rid });
	}

	let name = String(m.username ?? "").trim();
	let note = "";
	if (name === "all") {
		note = '"all" cannot be used as a username. Your username is generated by the server.';
		name = "";
	}
	if (!name) name = `agent[${pid}]`;

	const clash = find(name);
	if (clash && clash.pid !== pid) {
		return send(sock, { type: "error", message: `Username "${name}" is already in use by another agent.`, rid });
	}

	// Same pid = same pi process reconnecting or reloading: replace its old socket.
	for (const [other, u] of [...users]) {
		if (other !== sock && u.pid === pid) {
			users.delete(other);
			other.end();
		}
	}

	const task = String(m.task ?? "");
	users.set(sock, { sock, name, pid, cwd: String(m.cwd ?? ""), task });
	send(sock, { type: "registered", name, others: users.size - 1, note, rid });
	broadcast({ type: "presence", event: "online", name, task, ts: now() }, sock);
}

function onList(sock, rid) {
	if (!users.has(sock)) {
		return send(sock, { type: "error", message: "Not registered. Call agent_chat_register first.", rid });
	}
	send(sock, { type: "list", users: all().map(({ name, pid, cwd, task }) => ({ name, pid, cwd, task })), rid });
}

function onSend(sock, m, rid) {
	const me = users.get(sock);
	if (!me) {
		return send(sock, { type: "error", message: "Not registered. Call agent_chat_register first.", rid });
	}

	const raw = Array.isArray(m.targets) ? m.targets.map(String) : [];
	let targets = raw.includes("all") ? all().map((u) => u.name) : raw;
	// The sender is never a valid target: "all" excludes it, and explicitly
	// naming yourself is dropped the same way (a self-message could only ever
	// report "unread" and risks self-triggered feedback loops).
	targets = targets.filter((n) => n !== me.name);
	const text = String(m.text ?? "");
	if (targets.length === 0) {
		if (raw.length > 0 && !raw.includes("all")) {
			send(sock, { type: "error", message: "Cannot send a message to yourself.", code: "self", rid });
		} else {
			// Nothing to send, but still show the attempt on the server terminal.
			drawFrame({ from: me.name, text, status: new Map(), drawn: 0 });
			send(sock, { type: "sent", ok: [], unread: [], failed: [], rid });
		}
		return;
	}

	const ts = now();
	const mid = ++midCounter;
	const status = new Map();
	for (const t of targets) {
		const delivered = send(find(t)?.sock, { type: "message", from: me.name, text, ts, mid });
		status.set(t, delivered ? "pending" : "failed");
	}

	const p = { sock, rid, from: me.name, text, status, drawn: 0, finish: null };
	pendingSends.set(mid, p);
	drawFrame(p);

	p.finish = () => {
		// Drop the mapping first: after the reply, late acks are ignored.
		if (!pendingSends.delete(mid)) return;
		// Targets whose receiver never acked within the window (crashed or
		// legacy extension) get no report: count them as failed.
		for (const [t, v] of status) if (v === "pending") status.set(t, "failed");
		const pick = (stage) => [...status].filter(([, v]) => v === stage).map(([k]) => k);
		send(sock, { type: "sent", ok: pick("delivered"), unread: pick("buffered"), failed: pick("failed"), rid });
	};
	const timer = setTimeout(p.finish, ACK_WINDOW_MS);
	if (isSettled(p)) clearTimeout(timer), p.finish();
}

function onAck(sock, m) {
	const p = pendingSends.get(m.mid);
	const u = users.get(sock);
	if (!p || !u || !p.status.has(u.name)) return; // late or unknown: ignored
	const rank = RANK[m.stage];
	if (!rank || rank <= RANK[p.status.get(u.name)]) return;
	p.status.set(u.name, m.stage);
	drawFrame(p);
	if (isSettled(p)) p.finish();
}

const server = net.createServer((sock) => {
	sock.setEncoding("utf8");
	let buf = "";
	sock.on("data", (chunk) => {
		buf += chunk;
		for (let i; (i = buf.indexOf("\n")) >= 0; ) {
			const line = buf.slice(0, i).trim();
			buf = buf.slice(i + 1);
			if (line) handle(sock, line);
		}
	});
	// Socket close is the liveness signal: on localhost the OS closes the fd
	// even on kill -9, so no heartbeat protocol is needed.
	sock.on("close", () => {
		const u = users.get(sock);
		if (!u) return;
		users.delete(sock);
		broadcast({ type: "presence", event: "offline", name: u.name, task: u.task, ts: now() });
	});
	sock.on("error", () => {});
});

server.on("error", (e) => {
	console.error(`agent-chat server error: ${e.code ?? e.message}`);
	process.exit(1);
});

server.listen(PORT, HOST, () => {
	console.log(`agent-chat server listening on ${HOST}:${PORT} (pid ${process.pid})`);
});
